// <auto-generated />
namespace SF.Core.net46.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201707161129399_test-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
