// <auto-generated />
namespace SF.AdminSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbupgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbupgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171621375_db-upgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
