// <auto-generated />
namespace SF.AdminSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addserviceinstancetitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addserviceinstancetitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201702081334155_add-service-instance-title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
