// <auto-generated />
namespace SF.AdminSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adjustimpltypelength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustimpltypelength));
        
        string IMigrationMetadata.Id
        {
            get { return "201708030320272_adjust-impl-type-length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
