// <auto-generated />
namespace SF.AdminSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addmenuservice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmenuservice));
        
        string IMigrationMetadata.Id
        {
            get { return "201707291452494_add-menu-service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
